### ISSUE TITLE
API: start a new game

### ISSUE THREAD

**Issue by j2kun** [j2kun/lonely-hearts#59]
When all 4 players join a room, start a new game.

Figure out the user story for how a game is started.

**Comment by j2kun** [comment]
## Story for a user

 - Come to main page. 
 - Click "create new room"
 - Enter their name
 - Copy/paste url, and send to friends
 - Friends join room, pick names
 - After everyone picks names, game immediately starts?

## Details

1. When user joins a room, create a db entry for the player in the room. Unique id is stored on the user's session.
2. User is prompted to choose a name, and the sent to the server, and updated on the DB.

**Comment by DanielNghiem** [comment]
@j2kun : 

What if we ask all users for their name at the main page instead of in the room page?  And after the first user clicks "create a room", can we replace that button with another that says "join a room"?

**Comment by j2kun** [comment]
Another thing is that, the way most of these types of websites work, is when you create a new room (or collaborative document), the ID for that room is in the URL so you can just copy/paste the url to a friend, they can click it, and go straight to the action. Having a form before they get to the room is like a few extra steps that makes it kind of harder?

**Comment by DanielNghiem** [comment]
@j2kun:  I see two options in which to call the `create_game()` function: either it is triggered in the 'join' socket handler like so:
```
@socketio.on('join')
def on_join(data):
    # join the socketio room
    # update db.rooms
    room = get_room(room_id)
    if len(room['users']) == 4:
        create_game()
```

or I can make a new socket handler `@socketio.on('create_game')` separate from the action of joining a room.  

In the first option, the game will be automatically created without any user control (after joining a room).  The second option probably requires more work on the front end (requiring a user to click a "I'm ready" button or something), but at least we would know everyone is present and ready to play.  

I think I should go with the first option to keep it simple, but I'm wondering it there's any other reason why.

**Comment by j2kun** [comment]
I think the first option, and then right after the game is created, the `on_join` handler needs to

1. Start the game (I think you wrote all the logic that needs to happen in `game.start()`
2. For each player P,
  a. Serialize the game for P
  b. Emit the serialized game to the socket connection that exists just for P, using the action name we have to pick, how about `game_update`?

Note when a user creates the initial socket connection with the server, they automatically join a room all to themselves, and I think that room is automatically stored on the flask session object. So we can look up in the documentation how to emit to that socket.

I think once that's implemented in https://github.com/j2kun/lonely-hearts/pull/79 we can merge, or we could split step 2 into a subsequent PR.

**Comment by DanielNghiem** [comment]
Ok.  I will finish step 1 and test it in https://github.com/j2kun/lonely-hearts/pull/79 and save step 2 for another PR.
