### ISSUE TITLE
api/rooms: Users choose names when joining a room

### ISSUE THREAD

**Issue by j2kun** [j2kun/lonely-hearts#70]
When a user joins a room:

 - Server sends them an event through the websocket connection that is like "pick a name" or something
 - Client side javascript prompts the user to choose a name (we can start with a simple `alert` dialog) *Actually, I will handle the javascript! You just write the socket handlers, and write unit tests that test the flow, and then I will write the javascript part*
 - Client sends name back to server, and server updates the DB entry for that player with the player's chosen name.

This is where all the javascript for the socket api: https://github.com/j2kun/lonely-hearts/blob/master/hearts/static/socket_api.js

And where it's called: https://github.com/j2kun/lonely-hearts/blob/master/hearts/templates/room.html#L46

The calls should usually go in a separate file

**Comment by DanielNghiem** [comment]
@j2kun : In hearts/api/rest_views.py:  https://github.com/j2kun/lonely-hearts/blob/master/hearts/api/rest_views.py#L14-L22

What is the value of `room_id` ?  It looks like no document was inserted into db.rooms

**Comment by DanielNghiem** [comment]
Nevermind, I see that room_id is an ObjectID for the empty document.

**Comment by j2kun** [comment]
Yes, the return value of `insert` is always an objectID even if you insert an empty object

**Comment by j2kun** [comment]
This is also a good example of using `ipdb.set_trace()` to see what's inside a variable :)

**Comment by DanielNghiem** [comment]
The main cause of my confusion seems to come from the fact that some of the methods for mongo collections in our flask-pymongo differ from the documentation for PyMongo.  It's either that or the documentation is not clear enough for me to understand.   For example, `insert()` returns an ObjectID and `insert_one()` returns an `InsertOneResult` object, yet I can't find the insert() documentation on the Pymongo docs page.

**Comment by j2kun** [comment]
@DanielNghiem I think I can clear up the confusion. First two things:

 - Here is the complete documentation (called an API spec) for the python library. https://api.mongodb.com/python/current/api/index.html Every function is documented in one of these links, most importantly under [collection](https://api.mongodb.com/python/current/api/pymongo/collection.html)
 - The `insert` function is documented here https://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.insert

It appears that `insert` is a so-called "deprecated" function:

> DEPRECATED - Use insert_one() or insert_many() instead.

Deprecated means that they're slowly phasing it out until they delete it one day. They do it gradually to avoid breaking people's applications without giving them time to update. If I used `insert` somewhere, it's probably because I was reading an outdated tutorial.

So, in general, you should use `insert_one` and use those "results" objects as the documentation suggests.

**Comment by DanielNghiem** [comment]
@j2kun :  

On my branch in api/socket_events.py I have a socket event handler that updates a document in the mongo.db database. 

```
@socketio.on('join')
def on_join(data):
    username = data['username']
    room_id = data['room']

    io.join_room(room_id)
    session['room'] = room_id
    chat(username + ' has entered the room.', room=room_id)
    updated = mongo.db.rooms.update_one(
        {'_id': room_id},
        {'$push': {'users': username}}
        )
    if updated.acknowledged is True:
        data = mongo.db.rooms.find_one({'_id': room_id})
        return jsonify(data)
```

 I couple questions:

Since in `conftest.py` we have a pytest fixture that returns a test database `db`,  if I run a test function like this:

```
def test_on_join( socket_client, db):
    socket_client.emit('join', data)
```

will the `db` not be updated?  If not, is there a way to make this socket handler work with the test database (during testing) instead?

**Comment by j2kun** [comment]
I don't know for sure, but if the answer is that the db won't be properly updated, then I know the solution. In brief, it is to use a "singleton" pattern for the db object, and have a function in the hearts `__init__.py` that  looks at the settings to see if the db should be created as a test or production client.

**Comment by j2kun** [comment]
@DanielNghiem Could you push your local changes to your branch? I don't see your most recent changes

**Comment by j2kun** [comment]
@DanielNghiem Found the problem. Your query is:

```
---> 38     updated = mongo.db.rooms.update_one(
     39         {'_id': room_id},
     40         {'$push': {'users': username}}
     41         )
```

However, the actual contents of the db at that moment are:

```
ipdb> room = mongo.db.rooms.find({}).next()
ipdb> room
{'users': [], '_id': ObjectId('58f249af652943196f311dfc'), 'room_id': '12345'}
```

So this `_id` key is auto-generated by Mongo, and you can't control it. So either (a) in your test, get the object ID of the inserted room first, and then pass that to `emit`, or (b) change the query in the socket handler so that it queries based on `room_id`.

Personally, I don't care which we do, but using `room_id` will require us to maintain uniqueness among these ids by hand, whereas using Mongo ObjectID guarantees uniqueness for us.

Either way, I was looking at our code so far and it occurred to me that we should abstract away the basic functions that interact with the DB to some extent. For example, we should have a file called `rooms.py` with functions like `create_empty_room` and `add_user_to_room` that do the database interaction in a single place, and return the relevant data, and we can test/document those functions separately.

This will help in particular because, for example, in the socket tests you're writing right now, you're having to think too much about how to set up the proper state of the database before you actually test the thing you want to test. Too much thinking!
